### PR TITLE
fix(test): Isolate test-related babel config

### PR DESCRIPTION
**Pull request by brandonpayton**
The test-related `.babelrc` in the project root is interfering with dependent builds that use babel, indicating that the code should be instrumented via babel-plugin-espower.

Here is a sample of the error I'm seeing with webpack:
```
ERROR in /Users/.../stream-dom/~/most-subject/lib/index.js
Module build failed: ReferenceError: Unknown plugin "espower" specified in ...
```

IIUC, we only need to instrument the test modules for espower, and moving `.babelrc` to the `most-subject/test` folder addresses this issue since dependent builds won't typically reference test modules.

### CODE REVIEW

**Comment by TylorS** [comment]
LGTM

**Comment by TylorS** [comment]
@briancavalier @davidchase Can I get someone else to LGTM this? :) I can no longer force merge these as I don't have permission.

**Comment by davidchase** [comment]
LGTM 👍

**Comment by TylorS** [comment]
Hmmm, it doesn't seem to work still. @briancavalier I think that it might have to be you :/

**Comment by TylorS** [comment]
Thank you though @davidchase

**Comment by briancavalier** [comment]
LGTM

**Comment by briancavalier** [comment]
I wonder if LGTM has gotten confused after the repo was transferred?  We may have to disable and then re-enable it.

**Comment by briancavalier** [comment]
Ok, yeah, looking at the github webhook settings, github is trying to send webhook callbacks to lgtm, and lgtm is 404ing.  @TylorS, you'll probably have to disable and then re-setup lgtm for most-subject and most-proxy.  In the meantime, I made you an Owner, so you should be able to force-merge this PR via github (you can also do it via git command line and github will notice and reflect the merge status in the PR after you push the merge commit).

Let me know if you run into any more problems getting this merged or getting the webhook straightened out.

**Pull request merged**
